/*
 * Private pre-association SAE credential carrier for Tahoe WCL.
 *
 * This is not an Apple80211 public-key ABI or a UserClient ABI.  It is the
 * bounded project-owned handoff for the CIPHER_PWD value already present in a
 * Tahoe WCL association candidate before BSS selection begins.  The backend
 * copies this record synchronously into one private staging slot; no caller
 * pointer, PMK, PWE, KCK, cookie, or radio frame crosses this boundary.
 */
#ifndef _HAL_ITL_SAE_WCL_CREDENTIAL_V1_H_
#define _HAL_ITL_SAE_WCL_CREDENTIAL_V1_H_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

#include <HAL/ItlSaeAuthTransportV1.h>

#define kItlSaeWclCredentialV1Version 1u
#define kItlSaeWclCredentialV1SsidMaxLength 32u
#define kItlSaeWclCredentialV1PassphraseMinLength 8u
#define kItlSaeWclCredentialV1PassphraseMaxLength 63u
#define kItlSaeWclCredentialV1PasswordStorageLength 64u

/*
 * `request_generation` is generated by the WCL policy and is only a
 * cancellation/provenance fence.  SSID and BSSID are candidate constraints:
 * a later selected-BSS owner must bind them again before using a password.
 * The explicit zero tails make this fixed record safe to validate and scrub.
 */
struct ItlSaeWclCredentialV1 {
    uint32_t version;
    uint32_t size;
    uint64_t request_generation;
    uint32_t password_len;
    uint8_t ssid_len;
    uint8_t reserved0[3];
    uint8_t bssid[kItlSaeAuthTransportV1MacLength];
    uint8_t reserved1[2];
    uint8_t ssid[kItlSaeWclCredentialV1SsidMaxLength];
    uint8_t password[kItlSaeWclCredentialV1PasswordStorageLength];
    uint8_t reserved[8];
};

#if defined(__cplusplus)
#define ITL_SAE_WCL_CREDENTIAL_STATIC_ASSERT(condition, message) \
    static_assert((condition), message)
#else
#define ITL_SAE_WCL_CREDENTIAL_STATIC_ASSERT(condition, message) \
    _Static_assert((condition), message)
#endif

ITL_SAE_WCL_CREDENTIAL_STATIC_ASSERT(sizeof(struct ItlSaeWclCredentialV1) == 136,
    "SAE WCL credential ABI size");
ITL_SAE_WCL_CREDENTIAL_STATIC_ASSERT(offsetof(struct ItlSaeWclCredentialV1,
    request_generation) == 8, "SAE WCL credential generation offset");
ITL_SAE_WCL_CREDENTIAL_STATIC_ASSERT(offsetof(struct ItlSaeWclCredentialV1,
    password_len) == 16, "SAE WCL credential password length offset");
ITL_SAE_WCL_CREDENTIAL_STATIC_ASSERT(offsetof(struct ItlSaeWclCredentialV1,
    bssid) == 24, "SAE WCL credential BSSID offset");
ITL_SAE_WCL_CREDENTIAL_STATIC_ASSERT(offsetof(struct ItlSaeWclCredentialV1,
    ssid) == 32, "SAE WCL credential SSID offset");
ITL_SAE_WCL_CREDENTIAL_STATIC_ASSERT(offsetof(struct ItlSaeWclCredentialV1,
    password) == 64, "SAE WCL credential password offset");

static inline bool
itl_sae_wcl_credential_bytes_all_zero(const uint8_t *bytes, size_t length)
{
    size_t index;

    if (bytes == NULL)
        return true;
    for (index = 0; index < length; index++) {
        if (bytes[index] != 0)
            return false;
    }
    return true;
}

static inline bool
itl_sae_wcl_credential_bssid_is_unicast_nonzero(const uint8_t bssid[
    kItlSaeAuthTransportV1MacLength])
{
    return bssid != NULL && (bssid[0] & 0x01u) == 0 &&
        !itl_sae_wcl_credential_bytes_all_zero(bssid,
            kItlSaeAuthTransportV1MacLength);
}

static inline bool
itl_sae_wcl_credential_is_well_formed(
    const struct ItlSaeWclCredentialV1 *credential)
{
    return credential != NULL &&
        credential->version == kItlSaeWclCredentialV1Version &&
        credential->size == sizeof(*credential) &&
        credential->request_generation != 0 &&
        credential->ssid_len != 0 &&
        credential->ssid_len <= sizeof(credential->ssid) &&
        credential->password_len >=
            kItlSaeWclCredentialV1PassphraseMinLength &&
        credential->password_len <=
            kItlSaeWclCredentialV1PassphraseMaxLength &&
        itl_sae_wcl_credential_bssid_is_unicast_nonzero(credential->bssid) &&
        itl_sae_wcl_credential_bytes_all_zero(credential->reserved0,
            sizeof(credential->reserved0)) &&
        itl_sae_wcl_credential_bytes_all_zero(credential->reserved1,
            sizeof(credential->reserved1)) &&
        itl_sae_wcl_credential_bytes_all_zero(credential->ssid +
            credential->ssid_len, sizeof(credential->ssid) -
            credential->ssid_len) &&
        itl_sae_wcl_credential_bytes_all_zero(credential->password +
            credential->password_len, sizeof(credential->password) -
            credential->password_len) &&
        itl_sae_wcl_credential_bytes_all_zero(credential->reserved,
            sizeof(credential->reserved));
}

#endif /* _HAL_ITL_SAE_WCL_CREDENTIAL_V1_H_ */
